{% set name = "gpsd" %}
{% set version = "3.25" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://download.savannah.gnu.org/releases/{{ name }}/{{ name }}-{{ version }}.tar.xz
    sha256: 7e5e53e5ab157dce560a2f22e20322ef1136d3ebde99162def833a3306de01e5
    patches:
      - fix_build.patch

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('gpsd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('libudev') }}
    - {{ cdt('libudev-devel') }}
    - scons
  host:
    - python
    - libusb
    - ncurses
    - pyserial
    - matplotlib-base
  run:
    - python

test:
  commands:
    - test -f $PREFIX/lib/pkgconfig/libgps.pc  # [unix]
    - test -f $PREFIX/include/gps.h  # [unix]
    - test -f $PREFIX/bin/gpsfake  # [unix]


about:
  home: https://gpsd.io
  license: BSD-2-Clause
  license_file:
    - COPYING
  summary: gpsd is a service daemon that monitors one or more GPSes or AIS receivers attached to a host computer through serial or USB ports, making all data on the location/course/velocity of the sensors available to be queried on TCP port 2947 of the host computer.

extra:
  recipe-maintainers:
    - Tobias-Fischer
