{% set name = "gpsd" %}
{% set version = "3.26" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://download.savannah.gnu.org/releases/{{ name }}/{{ name }}-{{ version }}.zip
    sha256: d55f9f57c2f8449ffecdaaa9c39e32b38f306426021c3ac74da24cb03479dfd6
    patches:
      - fix_build.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('gpsd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - scons
  host:
    - python
    - libusb
    - libudev
    - ncurses
    - pyserial
    - matplotlib-base
  run:
    - python

test:
  commands:
    - test -f $PREFIX/lib/pkgconfig/libgps.pc  # [unix]
    - test -f $PREFIX/include/gps.h  # [unix]
    - test -f $PREFIX/bin/gpsfake  # [unix]


about:
  home: https://gpsd.io
  license: BSD-2-Clause
  license_file:
    - COPYING
  summary: gpsd is a service daemon that monitors one or more GPSes or AIS receivers attached to a host computer through serial or USB ports, making all data on the location/course/velocity of the sensors available to be queried on TCP port 2947 of the host computer.

extra:
  recipe-maintainers:
    - Tobias-Fischer
